theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

title: Mapi Piña - Software Engineering Manager
description: An empathetic software engineering manager focused on building scalable, reliable software and high-performing teams.
show_downloads: false
logo: /assets/img/logo.svg
github: mapipina
linkedin: mapipina
baseurl: "/portfolio" 
url: "https://mapipina.github.io" 
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true